name: CI/CD for Docker Hub

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']  # Fixed typo from 'mian' to 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Indented to match the structure

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Fixed typo from 'use' to 'uses'
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Run tests
        run: |
          pytest

  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      - name: Image digest
        run: echo ${{ steps.build-and-publish.outputs.digest }}
